# Generated by Django 5.1.3 on 2025-04-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('genome_length', models.IntegerField()),
                ('mutation_rate', models.FloatField()),
                ('quality', models.IntegerField()),
                ('iterations', models.IntegerField()),
                ('last_alive', models.BooleanField()),
                ('min_fitness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness', models.FloatField()),
                ('genome', models.TextField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation_app.simulation')),
            ],
        ),
    ]
